# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LumiHome' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  platform :ios, '8.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod "CocoaSSDP"
  # Pods for LumiHome

  target 'LumiHomeTests' do
    platform :ios, '8.0'
    inherit! :search_paths
    # Pods for testing
  end

end
